In [2]:
import pandas as pd
from ydata_profiling import ProfileReport

In [3]:
df = pd.read_csv('Sample Data Technical Test Markethac Aug 2024.csv')

In [4]:
df.head()

,date,itemid,channel,listingname,salescount,daily_sales_count,daily_sales_value,categorychannel,shopname,city,province,rating,ratecount,remainstock,discount,saleprice,salestype,fsid,fsstart
0,2023-05-08,1729385653806401294,Tiktok,Sunscren Madame gie SPF 30 PA +++,452,3,98262,Facial Sunscreen & Sun Care,galerybeautysemarang,NaN,NaN,4.0,82.0,258,0,32754,regular sales,NaN,NaN
1,2023-05-08,1729510593066469833,Tiktok,SKINTIFIC All Day Light Sunscreen Mist SPF50 P...,183,1,89600,Facial Sunscreen & Sun Care,CL Beauty Library,NaN,NaN,4.0,36.0,23,0,89600,regular sales,NaN,NaN
2,2023-05-08,1729582821264689500,Tiktok,LAMEILA SVMY Sunscreen Sun Block Wajah SPF 50 ...,61,2,25200,Facial Sunscreen & Sun Care,Kooala Store,NaN,NaN,4.0,9.0,941,0,12600,regular sales,NaN,NaN
3,2023-05-08,11804054885,Shopee,EMINA Sun Battle SPF 30 PA+++ sunscreen 60 ml,873,4,54000,Sunscreen Wajah,byaroona,Batu,Jawa Timur,4.0,282.0,1,21,13500,regular sales,NaN,NaN
4,2023-05-08,21120947258,Shopee,FACETOLOGY Triple Care Sunscreen SPF 40+ PA+++...,14,1,74999,Sunscreen Wajah,gufy.official,Batu,Jawa Timur,5.0,2.0,986,0,74999,regular sales,NaN,NaN

In [8]:
df_1 = df.sample(frac=0.1, random_state=42)

In [9]:
df_1.shape

(98139, 19)

In [10]:
df_1.to_csv('sample_test.csv')